---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsvc-deployment
  labels:
    app: microsvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microsvc
  template:
    metadata:
      labels:
        app: microsvc
    spec:
      containers:
        - name: microsvc
          image: localhost:32000/microsvc
          # Never
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password     
            - name: MONGODB_HOST
              value: "mongo-service"
            - name: MONGODB_PORT
              value: "27017"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microsvc
  name: microsvc-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30333
  selector:
    app: microsvc
  type: LoadBalancer