---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
        - name: job
          image: localhost:32000/job
          command: ["python", "job.py"]
          imagePullPolicy: Always
      restartPolicy: Never # Container may also restart on failure
  # backoffLimit: 2 # Number of retries before failure. default: 6 times
  completions: 10  # Number of sucessful executions
  parallelism: 3  # Number of parallel executions 