---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator
  labels:
    app: moderator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator
  template:
    metadata:
      labels:
        app: moderator
    spec:
      containers:
        - name: moderator
          image: localhost:32000/status
          command: ["python", "-m", "app.moderator"]
          imagePullPolicy: Always
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password     
            - name: MONGODB_HOST
              value: "mongo-service"
            - name: MONGODB_PORT
              value: "27017"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: CACHE_TTL
              value: "60"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: LOG_LEVEL
              value: "DEBUG"