---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
  labels:
    app: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: microsvc
          image: localhost:32000/status
          command: [ "uvicorn", "app.query:app", "--host", "0.0.0.0" ]
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password     
            - name: MONGODB_HOST
              value: "mongo-service"
            - name: MONGODB_PORT
              value: "27017"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: CACHE_TTL
              value: "60"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: LOG_LEVEL
              value: "DEBUG"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
            
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
  labels:
    app: query
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30333
  selector:
    app: query
  type: LoadBalancer